local recipes =
{
--liquids
{inputs = { liquidhealing=10 }, outputs = { fu_salt=3, fu_oxygen=1, fu_nitrogen=2 }, time = 0.1},
{inputs = { liquidwater=10 }, outputs = { fu_salt=2, fu_oxygen=2, fu_hydrogen=2 }, time = 0.1 },
{inputs = { swampwater=10 }, outputs = { fu_salt=2, fu_oxygen=2, fu_hydrogen=2 }, time = 0.1 },
{inputs = { liquiddarkwater=20 }, outputs = { fu_salt=3, fu_nitrogen=2, fu_carbon=1 }, time = 0.1 },
{inputs = { poop=1 }, outputs = { fu_nitrogen=5 }, time = 0.1 },
{inputs = { liquidpus=50 }, outputs = { fu_nitrogen=3 }, time = 0.1 },
{inputs = { algaegreen=5 }, outputs = { fu_nitrogen=3 }, time = 0.1 },
{inputs = { fu_nitrogen=1 }, outputs = { liquidnitrogenitem=2 }, time = 0.1 },
{inputs = { liquidnitrogenitem=1 }, outputs = { fu_nitrogen=2 }, time = 0.1 },
{inputs = { liquidblood=1 }, outputs = { fu_oxygen=2 }, time = 0.1 },
{inputs = { liquidironfu=25 }, outputs = { fu_carbon=2 }, time = 0.1 },
{inputs = { liquidpus=1 }, outputs = { fu_oxygen=2 }, time = 0.1 },
{inputs = { liquidblacktar=1 }, outputs = { liquidoil=2 }, time = 0.1 },
{inputs = { liquidbioooze=25 }, outputs = { fu_hydrogen=2 }, time = 0.1 },
{inputs = { liquidorganicsoup=25 }, outputs = { geneticmaterial=3 }, time = 0.1 },
{inputs = { frozenwater=50 }, outputs = { liquidwater=1 }, time = 0.1 },
-- bees mod content
{inputs = { darkcomb=1 }, outputs = { shadowgasliquid=2 }, time = 0.1 },
{inputs = { normalcomb=1 }, outputs = { fu_liquidhoney=2 }, time = 0.1 },
{inputs = { arcticcomb=1 }, outputs = { ice=2 }, time = 0.1 },
{inputs = { aridcomb=1 }, outputs = { sand=2 }, time = 0.1 },
{inputs = { exceptionalcomb=1 }, outputs = { fu_liquidhoney=5 }, time = 0.1 },
{inputs = { flowercomb=1 }, outputs = { liquidorganicsoup=2 }, time = 0.1 },
{inputs = { forestcomb=1 }, outputs = { fu_liquidhoney=2 }, time = 0.1 },
{inputs = { godlycomb=1 }, outputs = { solariumore=2 }, time = 0.1 },
{inputs = { silkcomb=1 }, outputs = { beesilk=1 }, time = 0.1 },
{inputs = { junglecomb=1 }, outputs = { biospore=2 }, time = 0.1 },
{inputs = { coppercomb=1 }, outputs = { copperore=2 }, time = 0.1 },
{inputs = { goldcomb=1 }, outputs = { goldore=2 }, time = 0.1 },
{inputs = { ironcomb=1 }, outputs = { ironore=2 }, time = 0.1 },
{inputs = { preciouscomb=1 }, outputs = { diamond=1 }, time = 0.1 },
{inputs = { silvercomb=1 }, outputs = { silverore=2 }, time = 0.1 },
{inputs = { titaniumcomb=1 }, outputs = { titaniumore=2 }, time = 0.1 },
{inputs = { mooncomb=1 }, outputs = { helium3gasliquid=2 }, time = 0.1 },
{inputs = { morbidcomb=1 }, outputs = { rottingfleshmaterial=2 }, time = 0.91 },
{inputs = { mythicalcomb=1 }, outputs = { vialproto=2 }, time = 0.1 },
{inputs = { nocturnalcomb=1 }, outputs = { shadowgasliquid=2 }, time = 0.1 },
{inputs = { plutoniumcomb=1 }, outputs = { plutoniumore=2 }, time = 0.1 },
{inputs = { radioactivecomb=1 }, outputs = { uraniumore=2 }, time = 0.1 },
{inputs = { redcomb=1 }, outputs = { liquidblood=2 }, time = 0.1 },
{inputs = { solariumcomb=1 }, outputs = { solariumore=2 }, time = 0.1 },
{inputs = { suncomb=1 }, outputs = { solariumore=2 }, time = 0.1 },
{inputs = { volcaniccomb=1 }, outputs = { cinnabarore=2 }, time = 0.1 },
{inputs = { flowerblue=1 }, outputs = { fu_nitrogen=1 }, time = 0.1},
{inputs = { flowerred=1 }, outputs = { fu_nitrogen=1 }, time = 0.1},
{inputs = { flowerspring=1 }, outputs = { fu_nitrogen=1 }, time = 0.1},
{inputs = { floweryellow=1 }, outputs = { fu_nitrogen=1 }, time = 0.1},
{inputs = { adaptivedrone=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { adaptivequeen=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { aggressivedrone=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { aggressivequeen=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { arcticdrone=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { arcticqueen=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { ariddrone=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { aridqueen=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { exceptionaldrone=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { exceptionalqueen=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { flowerdrone=1 }, outputs = { fu_oxygen=4 }, time = 0.1},
{inputs = { flowerqueen=1 }, outputs = { fu_oxygen=4 }, time = 0.1},
{inputs = { forestdrone=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { forestqueen=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { godlydrone=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { godlyqueen=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { hardydrone=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { hardyqueen=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { hunterdrone=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { hunterqueen=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { jungledrone=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { junglequeen=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { minerdrone=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { minerqueen=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { nocturnaldrone=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { nocturnalqueen=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { normaldrone=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { normalqueen=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { plutoniumdrone=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { plutoniumqueen=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { radioactivedrone=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { radioactivequeen=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { reddrone=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { redqueen=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { solariumdrone=1 }, outputs = { solariumore=4 }, time = 0.1},
{inputs = { solariumqueen=1 }, outputs = { solariumore=4 }, time = 0.1},
{inputs = { sundrone=1 }, outputs = { solariumore=2 }, time = 0.1},
{inputs = { sunqueen=1 }, outputs = { solariumore=2 }, time = 0.1},
{inputs = { volcanicdrone=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { volcanicqueen=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
--vanilla bugs
{inputs = { ashsprite=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { aurorabee=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { beebug=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { blueback=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { brightstripe=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { butterbee=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { cinderfly=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { dewhopper=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { driftbell=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { dustmoth=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { fawnfly=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { fireflyspawner=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { fireygiant=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { flameroach=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { flyspawner=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { frostfleck=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { frostfly=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { gasgiant=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { glowbug=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { goldbug=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { greentip=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { heathugger=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { hivehog=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { icetip=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { lavahopper=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { muddancer=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { orphanfly=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { phoenixfly=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { polarmoth=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { redwing=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { sandclown=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { scuttleploom=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { seahornet=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { shadowmoth=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { shardwing=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { shellcreep=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { snowskater=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { stinkjack=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { sunskipper=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { testbug=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { thornbee=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { tidefly=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { vineclimber=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { wavebird=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
{inputs = { xenofly=1 }, outputs = { geneticmaterial=1 }, time = 0.1},
---- resources

{inputs = { tritium=2 }, outputs = { helium3cannister=2, toxicwaste=3 }, time = 0.1 },

{inputs = { rottenfood=1 }, outputs = { fu_mulch=3 }, time = 0.1 },
{inputs = { toxicwaste=5 }, outputs = { uraniumore=1 }, time = 0.1},
{inputs = { energywood=5 }, outputs = { fu_oxygen=5 }, time = 0.1},
{inputs = { alienweirdwood=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { alienwoodsap=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { ancientbones=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { artificialbrain=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { pelt=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { biosample=2 }, outputs = { dnasample=1 }, time = 0.1},
{inputs = { bolt=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { bone=1 }, outputs = { liquidoil=9 }, time = 0.1},
{inputs = { bottle=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { brain=1 }, outputs = { tissueculture=9 }, time = 0.1},
{inputs = { bugshell=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { larva=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { cellmateria=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { cellmatter=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { coralfragment=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { dragonbone=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { endomorphicjelly=1 }, outputs = { tissueculture=8 }, time = 0.1},
{inputs = { fabric=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { fossilore=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { fleshstrand=10 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { giantflowerpetal=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { gnome=1 }, outputs = { bone=4 }, time = 0.1},
{inputs = { laboil=1 }, outputs = { liquidoil=40 }, time = 0.1},
{inputs = { gunpowder=1 }, outputs = { saltpeter=4 }, time = 0.1},
{inputs = { inferiorbrain=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { leather=1 }, outputs = { geneticmaterial=16 }, time = 0.1},
{inputs = { metallic=1 }, outputs = { tissueculture=2 }, time = 0.1},
{inputs = { moltencore=1 }, outputs = { tissueculture=2 }, time = 0.1},
{inputs = { monsterplating=1 }, outputs = { geneticmaterial=2 }, time = 0.1},
{inputs = { paper=1 }, outputs = { tissueculture=2 }, time = 0.1},
{inputs = { petalred=1 }, outputs = { tissueculture=2 }, time = 0.1},
{inputs = { petalblue=1 }, outputs = { tissueculture=2 }, time = 0.1},
{inputs = { petalyellow=1 }, outputs = { tissueculture=2 }, time = 0.1},
{inputs = { reed=1 }, outputs = { tissueculture=2 }, time = 0.1},
{inputs = { seaweed=1 }, outputs = { tissueculture=2 }, time = 0.1},
{inputs = { ff_spareparts=2 }, outputs = { tungstenore=1 }, time = 0.1},
{inputs = { toxicwaste=1 }, outputs = { tissueculture=2 }, time = 0.1},
{inputs = { flesh=1 }, outputs = { tissueculture=2 }, time = 0.1},
{inputs = { florangiantpod=1 }, outputs = { agaranichor=8,geneticmaterial=36 }, time = 0.1},
{inputs = { floranopenpod1=1 }, outputs = { agaranichor=2,geneticmaterial=9 }, time = 0.1},
{inputs = { floranopenpod2=1 }, outputs = { agaranichor=2,geneticmaterial=9 }, time = 0.1},
{inputs = { floranpod1=1 }, outputs = { agaranichor=2,geneticmaterial=6 }, time = 0.1},
{inputs = { floranpod1=1 }, outputs = { agaranichor=2,geneticmaterial=6 }, time = 0.1},
{inputs = { floranpod1=1 }, outputs = { agaranichor=2,geneticmaterial=6 }, time = 0.1},
{inputs = { floranpodapex=1 }, outputs = { agaranichor=6,geneticmaterial=24 }, time = 0.1},
{inputs = { metalchunk=2 }, outputs = { tungstenbar=2 }, time = 0.1},
{inputs = { silkspider=1 }, outputs = { silk=2 }, time = 0.1},
{inputs = { silkworm=1 }, outputs = { silk=2 }, time = 0.1},
{inputs = { biospore=2 }, outputs = { tissueculture=2, fu_oxygen=2 }, time = 0.1},
{inputs = { ebonshard=1 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { ff_mercury=1 }, outputs = { coalore=2, ironore=2 }, time = 0.1},
{inputs = { ff_resin=1 }, outputs = { nutrientpaste=4 }, time = 0.1},
{inputs = { greenslime=1 }, outputs = { fu_oxygen=4, fu_hydrogen=2 }, time = 0.1},
{inputs = { fu_nodule=1 }, outputs = { tissueculture=8 }, time = 0.1},
{inputs = { mutavisksilk=5 }, outputs = { dnasample=2 }, time = 0.1},
{inputs = { obsidianshard=1 }, outputs = { ammoniumsulfate=2 }, time = 0.1},
{inputs = { ff_bambooshoot=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { blooddiamond=1 }, outputs = { quietusore=3 }, time = 0.1},
-- tiles
{inputs = { boneyflesh=50 }, outputs = { bone=4 }, time = 0.45},
{inputs = { aliensoil=50 }, outputs = { algaegreen=5 }, time = 0.1},
{inputs = { redsand2=50 }, outputs = { ff_silicon=3 }, time = 0.1},
{inputs = { retexdirt=50 }, outputs = { nutrientpaste=4 }, time = 0.1},
{inputs = { retexcobblestone=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { retexredsandstone=50 }, outputs = { phosphorus=3 }, time = 0.1},
{inputs = { retexaetherdust=50 }, outputs = { mineralsample=4 }, time = 0.1},
{inputs = { retexsandstone=50 }, outputs = { phosphorus=2 }, time = 0.1},
{inputs = { peglacigiantekblock=50 }, outputs = { durasteelore=2 }, time = 0.5},
{inputs = { peglacihexpane=50 }, outputs = { ff_plastic=5 }, time = 0.5},
{inputs = { peglaciinscribedpykreteblock=50 }, outputs = { tungstenore=4 }, time = 0.5},
{inputs = { peglacimetalblock=50 }, outputs = { tungstenore=2 }, time = 0.5},
{inputs = { peglacimetalpanel=50 }, outputs = { tungstenore=2 }, time = 0.5},
{inputs = { peglacimetalscreen=50 }, outputs = { tungstenore=2 }, time = 0.5},
{inputs = { peglacipykreteblock=50 }, outputs = { tungstenore=2 }, time = 0.5},
{inputs = { peglacipykretedecor=50 }, outputs = { tungstenore=2 }, time = 0.5},
{inputs = { hiveoldmaterial=50 }, outputs = { geneticmaterial=4 }, time = 0.3},
{inputs = { fumetalblockmaterial=50 }, outputs = { tungstenore=2 }, time = 0.5},
{inputs = { violiumcrystal=50 }, outputs = { ff_silicon=2 }, time = 0.1},
{inputs = { aegisaltcrystal=50 }, outputs = { ff_silicon=1 }, time = 0.45},
{inputs = { springvines=50 }, outputs = { geneticmaterial=3 }, time = 0.1},
{inputs = { andesite=50 }, outputs = { rawminerals=2 }, time = 0.1},
{inputs = { jellyblock=50 }, outputs = { endomorphicjelly=2 }, time = 0.1},
{inputs = { jellyblock=50 }, outputs = { endomorphicjelly=1 }, time = 0.1},
{inputs = { jellystone=50 }, outputs = { endomorphicjelly=2 }, time = 0.1},
{inputs = { redhotcobblestone=50 }, outputs = { corefragmentore=4 }, time = 0.1},
{inputs = { retexironblock=50 }, outputs = { tungstenore=2 }, time = 0.6},
{inputs = { retexironpipe=50 }, outputs = { tungstenore=2 }, time = 0.6},
{inputs = { avalichits=50 }, outputs = { fu_carbon=2 }, time = 0.6},
{inputs = { avalidarkmetal2=50 }, outputs = { ironore=2 }, time = 0.6},
{inputs = { avalihexagons1=50 }, outputs = { ff_silicon=2 }, time = 0.6},
{inputs = { avalitechpanel=50 }, outputs = { ff_plastic=2 }, time = 0.6},
{inputs = { geodeblock=50 }, outputs = { crystal=3 }, time = 0.1},
{inputs = { geodestone=50 }, outputs = { crystal=3 }, time = 0.1},
{inputs = { shadowwallblock=50 }, outputs = { rawminerals=5 }, time = 0.1},
{inputs = { shadowspikeblock=50 }, outputs = { rawminerals=53 }, time = 0.1},
{inputs = { shadowblock=50 }, outputs = { rawminerals=5 }, time = 0.1},
{inputs = { concretematerial=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { honeycombmaterial=50 }, outputs = { fu_liquidhoney=5 }, time = 0.1},
{inputs = { redhoneycombmaterial=50 }, outputs = { fu_liquidhoney=5 }, time = 0.1},
{inputs = { fu_honeycombblock=50 }, outputs = { fu_liquidhoney=4 }, time = 0.1},
{inputs = { fu_redhoneycombblock=50 }, outputs = { fu_liquidhoney=4 }, time = 0.1},
{inputs = { grassy=50 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { waste=50 }, outputs = { nutrientpaste=4 }, time = 0.1},
{inputs = { cactiblock=50 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { fumossyrock=50 }, outputs = { rawminerals=3 }, time = 0.1},
{inputs = { fumossyrock2=50 }, outputs = { rawminerals=3 }, time = 0.1},
{inputs = { biorock=50 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { biorock2=50 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { frozendirt=50 }, outputs = { nutrientpaste=5 }, time = 0.1},
{inputs = { grassyrock=50 }, outputs = { rawminerals=2 }, time = 0.1},
{inputs = { frozensandmaterial=50 }, outputs = { ff_silicon=3 }, time = 0.1},
{inputs = { frozensand2material=50 }, outputs = { ff_silicon=3 }, time = 0.1},
{inputs = { frozenstonematerial=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { steelstonematerial=50 }, outputs = { metalchunk=2 }, time = 0.1},
{inputs = { fungalstonematerial=50 }, outputs = { rawminerals=3 }, time = 0.1},
{inputs = { rainbowsandmaterial=50 }, outputs = { ff_silicon=4 }, time = 0.1},
{inputs = { glasssandmaterial=50 }, outputs = { ff_silicon=2 }, time = 0.1},
{inputs = { crystalsandmaterial=50 }, outputs = { ff_silicon=2 }, time = 0.1},
{inputs = { rottingfleshmaterial=50 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { tarstonematerial=50 }, outputs = { liquidblacktar=4 }, time = 0.1},
{inputs = { junglestonematerial=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { petalblock=50 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { floweryblock=50 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { stonerubble=50 }, outputs = { rawminerals=3 }, time = 0.1},
{inputs = { techhull1=50 }, outputs = { ironore=3 }, time = 0.1},
{inputs = { moltensteel=50 }, outputs = { metalchunk=2 }, time = 0.1},
{inputs = { moltenmetal=50 }, outputs = { metalchunk=2 }, time = 0.1},
{inputs = { moltensand=50 }, outputs = { metalchunk=2 }, time = 0.1},
{inputs = { moltentile=50 }, outputs = { metalchunk=2 }, time = 0.1},
{inputs = { steelsand=50 }, outputs = { metalchunk=2 }, time = 0.1},
{inputs = { steelpartblock=50 }, outputs = { metalchunk=2 }, time = 0.1},
{inputs = { steelmetal=50 }, outputs = { metalchunk=2 }, time = 0.1},
{inputs = { alienrock=50 }, outputs = { ff_silicon=4 }, time = 0.1},
{inputs = { harrowstone=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { genetile=50 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { warttile=50 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { alienstripedwood=50 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { alienstripedwood=50 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { blackslimematerial=8}, outputs = { blobbushjelly=2 }, time = 0.1},
{inputs = { bamboo=50 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { bonematerial=25 }, outputs = { bone=8, liquidoil=20 }, time = 0.1},
{inputs = { bonemealmaterial=50 }, outputs = { nutrientpaste=2 }, time = 0.1},
{inputs = { calichewall=6 }, outputs = { iodine=3,saltpeter=3 }, time = 0.1},
{inputs = { corruptslimematerial=50 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { eyepiles=50 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { andesitematerial=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { arkosematerial=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { ash=50 }, outputs = { nutrientpaste=4 }, time = 0.1},
{inputs = { bioblockmaterial=50 }, outputs = { geneticmaterial=2 }, time = 0.1},
{inputs = { bioblock2material=50 }, outputs = { geneticmaterial=2 }, time = 0.1},
{inputs = { biodirtmaterial=50 }, outputs = { fu_nitrogen=2 }, time = 0.1},
{inputs = { biogravelmaterial=50 }, outputs = { tissueculture=2 }, time = 0.1},
{inputs = { biostonematerial=50 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { blaststone=50 }, outputs = { rawminerals=6 }, time = 0.1},
{inputs = { bloodsandmaterial=50 }, outputs = { liquidoil=4 }, time = 0.1},
{inputs = { bloodstonewall=50 }, outputs = { blooddiamond=2 }, time = 0.1},
{inputs = { bloodstonewall2=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { bloodstonewall3=50 }, outputs = { phosphorus=2 }, time = 0.1},
{inputs = { bloodstonematerial=50 }, outputs = { phosphorus=3 }, time = 0.1},
{inputs = { brainsblock=50 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { brick=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { castlewalls1=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { castlewalls2=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { chertmaterial=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { clay=50 }, outputs = { nutrientpaste=5 }, time = 0.1},
{inputs = { cloudblock=50 }, outputs = { liquidwater=4 }, time = 0.1},
{inputs = { cobblestone=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { cobblestonematerial=50 }, outputs = { rawminerals=3 }, time = 0.1},
{inputs = { conglomeratematerial=50 }, outputs = { rawminerals=3 }, time = 0.1},
{inputs = { corruptmaterial=50 }, outputs = { nutrientpaste=3 }, time = 0.1},
{inputs = { corruptdirtmaterial=50 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { crystal=50 }, outputs = { icecrystal=2 }, time = 0.1},
{inputs = { crystalblock=50 }, outputs = { crystal=4 }, time = 0.1},
{inputs = { dacitematerial=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { darknessmaterial=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { darkstonematerial=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { direstone=50 }, outputs = { rawminerals=8 }, time = 0.1},
{inputs = { dirtmaterial=50 }, outputs = { nutrientpaste=5 }, time = 0.1},
{inputs = { drydirt=50 }, outputs = { nutrientpaste=4 }, time = 0.1},
{inputs = { drysand=50 }, outputs = { liquidoil=4, iodine=2 }, time = 0.1},
{inputs = { fleshblock=50 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { gabbromaterial=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { glowsandmaterial=50 }, outputs = { ff_silicon=2 }, time = 0.1},
{inputs = { gneissmaterial=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { gravelmaterial=50 }, outputs = { rawminerals=3 }, time = 0.1},
{inputs = { gritstonematerial=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { hellstonematerial=50 }, outputs = { rawminerals=6, iodine=2 }, time = 0.1},
{inputs = { hive=50 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { ice=50 }, outputs = { nutrientpaste=2, liquidwater=12 }, time = 0.1},
{inputs = { iceblock1material=50 }, outputs = { liquidwater=12, fu_nitrogen=2 }, time = 0.1},
{inputs = { iceblock2material=50 }, outputs = { liquidwater=12, fu_nitrogen=2 }, time = 0.1},
{inputs = { iceblock3material=50 }, outputs = { liquidwater=12, fu_nitrogen=2 }, time = 0.1},
{inputs = { iceblock4material=50 }, outputs = { liquidwater=12, fu_nitrogen=2 }, time = 0.1},
{inputs = { icecrystal=5 }, outputs = { crystal=55 }, time = 0.1},
{inputs = { irradiatedwall=50 }, outputs = { uraniumore=2 }, time = 0.1},
{inputs = { irradiatedwall2=50 }, outputs = { rawminerals=3 }, time = 0.1},
{inputs = { irradiatedwall3=50 }, outputs = { uraniumore=2 }, time = 0.1},
{inputs = { chromadirtmaterial=50 }, outputs = { fu_carbon=2 }, time = 0.1},
{inputs = { jungledirt1material=50 }, outputs = { fu_mulch=3 }, time = 0.1},
{inputs = { jungledirt2material=50 }, outputs = { fu_nitrogen=4, fu_oxygen=3 }, time = 0.1},
{inputs = { limestonematerial=50 }, outputs = { rawminerals=4, calciumnitrate=1 }, time = 0.1},
{inputs = { magmarock=50 }, outputs = { ammoniumsulfate=2 }, time = 0.1},
{inputs = { magmawall1=50 }, outputs = { ammoniumsulfate=4 }, time = 0.1},
{inputs = { magmawall2=50 }, outputs = { rawminerals=4, corefragmentore=2 }, time = 0.1},
{inputs = { magmawall3=50 }, outputs = { rawminerals=5, corefragmentore=2 }, time = 0.1},
{inputs = { magmawall4=50 }, outputs = { ammoniumsulfate=2 }, time = 0.1},
{inputs = { marestonematerial=50 }, outputs = { rawminerals=2, iodine=4 }, time = 0.1},
{inputs = { meteoriterock=50 }, outputs = { ff_silicon=2 }, time = 0.1},
{inputs = { moondust=50 }, outputs = { helium3cannister=4 }, time = 0.1},
{inputs = { moonrock=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { moonstone=50 }, outputs = { rawminerals=3 }, time = 0.1},
{inputs = { mossypackeddirt=50 }, outputs = { fu_nitrogen=4 }, time = 0.1},
{inputs = { mud=50 }, outputs = { nutrientpaste=2 }, time = 0.1},
{inputs = { mudstonematerial=50 }, outputs = { rawminerals=3 }, time = 0.1},
{inputs = { obsidian=10 }, outputs = { obsidianshard=2 }, time = 0.1},
{inputs = { packeddirt=50 }, outputs = { nutrientpaste=2 }, time = 0.1},
{inputs = { penumbradirtmaterial=30 }, outputs = { nutrientpaste=2 }, time = 0.1},
{inputs = { penumbrastonematerial=30 }, outputs = { rawminerals=2 }, time = 0.1},
{inputs = { plantblock=50 }, outputs = { tissueculture=4, fu_oxygen=3 }, time = 0.1},
{inputs = { plantmatter=50 }, outputs = { fu_mulch=4, fu_oxygen=3 }, time = 0.1},
{inputs = { purplecrystalmaterial=50 }, outputs = { ff_silicon=3 }, time = 0.1},
{inputs = { raincloudmat=50 }, outputs = { liquidwater=5 }, time = 0.1},
{inputs = { redsand=50 }, outputs = { ff_silicon=2 }, time = 0.1},
{inputs = { sand=50 }, outputs = { ff_silicon=2 }, time = 0.1},
{inputs = { sand2=50 }, outputs = { ff_silicon=2 }, time = 0.1},
{inputs = { sandstonematerial=50 }, outputs = { phosphorus=2 }, time = 0.1},
{inputs = { sandstoneblock=50 }, outputs = { phosphorus=2 }, time = 0.1},
{inputs = { sewage=50 }, outputs = { poop=4 }, time = 0.1},
{inputs = { shroom=5 }, outputs = { nutrientpaste=4 }, time = 0.1},
{inputs = { shroomblock=50 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { slime=50 }, outputs = { nutrientpaste=4 }, time = 0.1},
{inputs = { slime2material=50 }, outputs = { greenslime=2 }, time = 0.1},
{inputs = { slush=50 }, outputs = { nutrientpaste=2 }, time = 0.1},
{inputs = { snow=50 }, outputs = { nutrientpaste=4 }, time = 0.1},
{inputs = { junk=50 }, outputs = { ff_silicon=2, ironore=2 }, time = 0.1},
{inputs = { rustymetal=50 }, outputs = { ironore=2 }, time = 0.1},
{inputs = { sulphurdirtmaterial=50 }, outputs = { rawminerals=4, sulphur=3 }, time = 0.1},
{inputs = { sulphurstonematerial=50 }, outputs = { rawminerals=5, sulphur=3 }, time = 0.1},
{inputs = { swampdirtffmaterial=50 }, outputs = { nutrientpaste=3, fu_oxygen=2 }, time = 0.1},
{inputs = { tar=50 }, outputs = { liquidoil=4 }, time = 0.1},
{inputs = { wastestone=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { wetdirt=50 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { logblock=5 }, outputs = { methanol=4 }, time = 0.1},
{inputs = { shroomblockglow=50 }, outputs = { agaranichor=4 }, time = 0.1},
{inputs = { slimedirtmaterial=50 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { spidersilkblock=50 }, outputs = { silk=3 }, time = 0.1},
{inputs = { supermatter=4 }, outputs = { liquidfuel=5 }, time = 0.1},
{inputs = { coralmaterial=50 }, outputs = { coralfragment=3 }, time = 0.1},
{inputs = { coral2material=50 }, outputs = { coralfragment=3 }, time = 0.1},
{inputs = { diamondblockmaterial=10 }, outputs = { diamond=1 }, time = 0.1},
{inputs = { sulphurdirtmaterial=50 }, outputs = { rawminerals=5 }, time = 0.1},
{inputs = { brittlejunk=50 }, outputs = { rawminerals=3 }, time = 0.1},
{inputs = { brittlemetal=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { marestonematerial=50 }, outputs = { rawminerals=3 }, time = 0.1},
{inputs = { oystershellmaterial=50 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { rostonematerial=50 }, outputs = { rawminerals=4 }, time = 0.1},
{inputs = { ebonblockmaterial=4 }, outputs = { ebonshard=5 }, time = 0.1},
{inputs = { elderblockmaterial=50 }, outputs = { rawminerals=5 }, time = 0.1},
{inputs = { elderblock2material=50 }, outputs = { rawminerals=5 }, time = 0.1},
{inputs = { elderstonematerial=50 }, outputs = { rawminerals=5 }, time = 0.1},
{inputs = { elderstone2material=50 }, outputs = { rawminerals=5 }, time = 0.1},
{inputs = { energywood=50 }, outputs = { penumbriteore=2 }, time = 0.1},
{inputs = { vine=50 }, outputs = { plantfibre=4, fu_oxygen=1 }, time = 0.1},
-- seeds
{inputs = { cocoaseed=1 }, outputs = { tissueculture=3 }, time = 0.1},
{inputs = { wildcocoaseed=1 }, outputs = { tissueculture=3 }, time = 0.1},
{inputs = { cottonseed=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { cinnamonseed=1 }, outputs = { fu_nitrogen=4 }, time = 0.1},
{inputs = { algaeseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { automatoseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { avesmingoseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { bananaseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { beetlesproutseed=1 }, outputs = { algaeseed=3 }, time = 0.1},
{inputs = { beakseedseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { biscornseed=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { garpberryseed=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { garpberry=4 }, outputs = { aliencompound=2 }, time = 0.1},
{inputs = { blizzberryseed=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { bloodrootseed=1 }, outputs = { liquidblood=5 }, time = 0.1},
{inputs = { bluemelonseed=1 }, outputs = { geneticmaterial=3 }, time = 0.1},
{inputs = { blexplantseed=1 }, outputs = { ff_resin=3 }, time = 0.1},
{inputs = { boltbulbseed=1 }, outputs = { coil=2 }, time = 0.1},
{inputs = { bonebooseed=1 }, outputs = { bone=3 }, time = 0.1},
{inputs = { brackentreeseed=1 }, outputs = { silk=5 }, time = 0.1},
{inputs = { aquapodseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { bambooseed=1 }, outputs = { geneticmaterial=4 }, time = 1 },
{inputs = { blisterbushplantseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { caprioleplantseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { carrotseed=1 }, outputs = { cellmateria=3 }, time = 0.1},
{inputs = { chiliseed=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { coffeeseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { coralcreepseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { cornseed=1 }, outputs = { geneticmaterial=2 }, time = 0.1},
{inputs = { corvexseed=1 }, outputs = { corvex=2 }, time = 0.1},
{inputs = { crystalplantseed=1 }, outputs = { crystal=2 }, time = 0.1},
{inputs = { currentcornseed=1 }, outputs = { ff_silicon=2 }, time = 0.1},
{inputs = { deathblossomseed=1 }, outputs = { biospore=5 }, time = 0.1},
{inputs = { diodiaseed=1 }, outputs = { geneticmaterial=3 }, time = 0.1},
{inputs = { diodiahybridseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { dirturchinseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { dragonsbeardseed=1 }, outputs = { ammoniumsulfate=2 }, time = 0.1},
{inputs = { energiflowerseed=1 }, outputs = { plantfibre=12 }, time = 0.1},
{inputs = { erithianalgaeseed=1 }, outputs = { algaeseed=3 }, time = 0.1},
{inputs = { eggshootseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { feathercrownseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { flowerblueseed=1 }, outputs = { geneticmaterial=3 }, time = 0.1},
{inputs = { flowerredseed=1 }, outputs = { geneticmaterial=3 }, time = 0.1},
{inputs = { floweryellowseed=1 }, outputs = { geneticmaterial=3 }, time = 0.1},
{inputs = { floralytplantseed=1 }, outputs = { geneticmaterial=18 }, time = 0.1},
{inputs = { fubioshroomblue=1 }, outputs = { biospore=5 }, time = 0.1},
{inputs = { fubioshroomgreen=1 }, outputs = { biospore=5 }, time = 0.1},
{inputs = { fubioshroompurple=1 }, outputs = { biospore=5 }, time = 0.1},
{inputs = { fubioshroomred=1 }, outputs = { biospore=5 }, time = 0.1},
{inputs = { fubioshroomyellow=1 }, outputs = { biospore=5 }, time = 0.1},
{inputs = { fayshroomseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { ghostmushroomseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { ginsengseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { goldenrootseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { goldshroomseed=1 }, outputs = { goldore=6 }, time = 0.1},
{inputs = { greenleafseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { guamseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { gazelemonseed=1 }, outputs = { tissueculture=6 }, time = 0.1},
{inputs = { glarestalkseed=1 }, outputs = { eyepiles=13 }, time = 0.1},
{inputs = { genesiberryseed=1 }, outputs = { tissueculture=18 }, time = 0.1},
{inputs = { goldenglowseed=1 }, outputs = { geneticmaterial=8 }, time = 0.1},
{inputs = { grapesseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { haleflowerseed=1 }, outputs = { geneticmaterial=7 }, time = 0.1},
{inputs = { hopsseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { hellfireplantseed=1 }, outputs = { ammoniumsulfate=15 }, time = 0.1},
{inputs = { ighantseed=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { ignuschiliseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { ignuschili2seed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { itaseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { jillyrootseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { kiwiseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { lasherplantseed=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { leafshellseed=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { lactariusindigoseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { vanusflowerseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { littlerascalseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { littlegoodberryseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { melodistarseed=1 }, outputs = { geneticmaterial=7 }, time = 0.1},
{inputs = { minkocoapodseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { mintseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { miraclegrassseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { mireurchinseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { mutaviskseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { neonmelonseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { nissseed=1 }, outputs = { tissueculture=6 }, time = 0.1},
{inputs = { naileryseed=1 }, outputs = { rawminerals=6 }, time = 0.1},
{inputs = { neuropodseed=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { oculemonseed=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { mutaviskseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { oonfortaseed=1 }, outputs = { biospore=3 }, time = 0.1},
{inputs = { pasakavineseed=1 }, outputs = { tissueculture=3 }, time = 0.1},
{inputs = { pekkitseed=1 }, outputs = { tissueculture=7, fu_nitrogen=2 }, time = 0.1},
{inputs = { petrifiedrootseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { pinkloomseed=1 }, outputs = { geneticmaterial=7 }, time = 0.1},
{inputs = { pearlpeaseed=1 }, outputs = { geneticmaterial=7 }, time = 0.1},
{inputs = { pineappleseed=1 }, outputs = { geneticmaterial=7 }, time = 0.1},
{inputs = { potatoseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { porphisplantseed=1 }, outputs = { tissueculture=7 }, time = 0.1},
{inputs = { pussplumseed=1 }, outputs = { tissueculture=7 }, time = 0.1},
{inputs = { reefpodseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { rockrootseed=1 }, outputs = { rawminerals=7 }, time = 0.1},
{inputs = { riceseed=1 }, outputs = { geneticmaterial=7 }, time = 0.1},
{inputs = { sapling=1 }, outputs = { tissueculture=7, fu_oxygen=3 }, time = 0.1},
{inputs = { shinyacornseed=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { shockshroomseed=1 }, outputs = { tissueculture=11 }, time = 0.1},
{inputs = { silverleafseed=1 }, outputs = { silverore=4 }, time = 0.1},
{inputs = { slimeplantseed=1 }, outputs = { greenslime=5 }, time = 0.1},
{inputs = { springvaultseed=1 }, outputs = { tissueculture=3 }, time = 0.1},
{inputs = { stranglevineseed=1 }, outputs = { tissueculture=6 }, time = 0.1},
{inputs = { sugarcaneseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { teratomatoseed=1 }, outputs = { geneticmaterial=13 }, time = 0.1},
{inputs = { talonseedseed=1 }, outputs = { geneticmaterial=7 }, time = 0.1},
{inputs = { tetherhookseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { thornitoxseed=1 }, outputs = { geneticmaterial=7 }, time = 0.1},
{inputs = { tomatoseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { toxictopseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { tyvokkseed=1 }, outputs = { geneticmaterial=8 }, time = 0.1},
{inputs = { varanberryseed=1 }, outputs = { geneticmaterial=2 }, time = 0.1},
{inputs = { vextongueseed=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { voritseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { wartweedseed=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { wheatseed=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { vashtaplantseed=1 }, outputs = { tissueculture=7 }, time = 0.1},
{inputs = { wretchelseed=1 }, outputs = { tissueculture=11 }, time = 0.1},
{inputs = { wubstemseed=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { xaxseed=1 }, outputs = { tissueculture=7 }, time = 0.1},
{inputs = { yellowfootseed=1 }, outputs = { tissueculture=7 }, time = 0.1},
{inputs = { zathiseed=1 }, outputs = { geneticmaterial=9 }, time = 0.1},
{inputs = { kamaranpodsplant=1 }, outputs = { geneticmaterial=8 }, time = 5},
{inputs = { cellpodsplant=1 }, outputs = { geneticmaterial=7 }, time = 5},
{inputs = { goldenseaspongeplant=1 }, outputs = { tissueculture=7 }, time = 5},
{inputs = { fusnowberryseed=1 }, outputs = { tissueculture=8 }, time = 5},
{inputs = { fuspongeweedseed=1 }, outputs = { geneticmaterial=7 }, time = 5},
{inputs = { wildalgaeseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { wildautomatoseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { wildavesmingoseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { wildbananaseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { wildbeetlesproutseed=1 }, outputs = { algaeseed=3 }, time = 0.1},
{inputs = { wildbeakseedseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { wildbiospore=1}, outputs = { shroom=3 }, time = 0.1},
{inputs = { wildbiscornseed=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { wildblizzberryseed=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { wildbloodrootseed=1 }, outputs = { liquidblood=5 }, time = 0.1},
{inputs = { wildbluemelonseed=1 }, outputs = { geneticmaterial=3 }, time = 0.1},
{inputs = { wildblexplantseed=1 }, outputs = { ff_resin=3 }, time = 0.1},
{inputs = { wildboltbulbseed=1 }, outputs = { coil=2 }, time = 0.1},
{inputs = { wildbonebooseed=1 }, outputs = { bone=3 }, time = 0.1},
{inputs = { wildbrackentreeseed=1 }, outputs = { silk=5 }, time = 0.1},
{inputs = { wildaquapodseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { wildbambooseed=1 }, outputs = { geneticmaterial=4 }, time = 1 },
{inputs = { wildblisterbushplantseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { wildcaprioleplantseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { wildcarrotseed=1 }, outputs = { cellmateria=3 }, time = 0.1},
{inputs = { wildchiliseed=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { wildcoffeeseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { wildcoralcreepseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { wildcornseed=1 }, outputs = { geneticmaterial=2 }, time = 0.1},
{inputs = { wildcorvexseed=1 }, outputs = { corvex=2 }, time = 0.1},
{inputs = { wildcrystalplantseed=1 }, outputs = { crystal=2 }, time = 0.1},
{inputs = { wildcurrentcornseed=1 }, outputs = { ff_silicon=2 }, time = 0.1},
{inputs = { wilddeathblossomseed=1 }, outputs = { biospore=5 }, time = 0.1},
{inputs = { wilddiodiaseed=1 }, outputs = { geneticmaterial=3 }, time = 0.1},
{inputs = { wilddiodiahybridseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { wilddirturchinseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { wilddragonsbeardseed=1 }, outputs = { ammoniumsulfate=2 }, time = 0.1},
{inputs = { wildenergiflowerseed=1 }, outputs = { plantfibre=12 }, time = 0.1},
{inputs = { wilderithianalgaeseed=1 }, outputs = { algaeseed=3 }, time = 0.1},
{inputs = { wildeggshootseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { wildfeathercrownseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { wildflowerblueseed=1 }, outputs = { geneticmaterial=3 }, time = 0.1},
{inputs = { wildflowerredseed=1 }, outputs = { geneticmaterial=3 }, time = 0.1},
{inputs = { wildfloweryellowseed=1 }, outputs = { geneticmaterial=3 }, time = 0.1},
{inputs = { wildfloralytplantseed=1 }, outputs = { geneticmaterial=18 }, time = 0.1},
{inputs = { wildfubioshroomblue=1 }, outputs = { biospore=5 }, time = 0.1},
{inputs = { wildfubioshroomgreen=1 }, outputs = { biospore=5 }, time = 0.1},
{inputs = { wildfubioshroompurple=1 }, outputs = { biospore=5 }, time = 0.1},
{inputs = { wildfubioshroomred=1 }, outputs = { biospore=5 }, time = 0.1},
{inputs = { wildfubioshroomyellow=1 }, outputs = { biospore=5 }, time = 0.1},
{inputs = { wildfayshroomseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { wildghostmushroomseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { wildginsengseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { wildgoldenrootseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { wildgoldshroomseed=1 }, outputs = { goldore=6 }, time = 0.1},
{inputs = { wildgreenleafseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { wildguamseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { wildgazelemonseed=1 }, outputs = { tissueculture=6 }, time = 0.1},
{inputs = { wildglarestalkseed=1 }, outputs = { eyepiles=13 }, time = 0.1},
{inputs = { wildgenesiberryseed=1 }, outputs = { tissueculture=18 }, time = 0.1},
{inputs = { wildgoldenglowseed=1 }, outputs = { geneticmaterial=8 }, time = 0.1},
{inputs = { wildgrapesseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { wildhaleflowerseed=1 }, outputs = { geneticmaterial=7 }, time = 0.1},
{inputs = { wildhopsseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { wildhellfireplantseed=1 }, outputs = { ammoniumsulfate=15 }, time = 0.1},
{inputs = { wildighantseed=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { wildignuschiliseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { wildignuschili2seed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { wilditaseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { wildjillyrootseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { wildkiwiseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { wildlasherplantseed=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { wildleafshellseed=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { wildlactariusindigoseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { wildvanusflowerseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { wildlittlerascalseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { wildlittlegoodberryseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { wildmelodistarseed=1 }, outputs = { geneticmaterial=7 }, time = 0.1},
{inputs = { wildminkocoapodseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { wildmintseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { wildmiraclegrassseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { wildmireurchinseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { wildmutaviskseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { wildneonmelonseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { wildnissseed=1 }, outputs = { tissueculture=6 }, time = 0.1},
{inputs = { wildnaileryseed=1 }, outputs = { rawminerals=6 }, time = 0.1},
{inputs = { wildneuropodseed=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { wildoculemonseed=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { wildmutaviskseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { wildoonfortaseed=1 }, outputs = { biospore=3 }, time = 0.1},
{inputs = { wildpasakavineseed=1 }, outputs = { tissueculture=3 }, time = 0.1},
{inputs = { wildpekkitseed=1 }, outputs = { tissueculture=7 }, time = 0.1},
{inputs = { wildpetrifiedrootseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { wildpinkloomseed=1 }, outputs = { geneticmaterial=7 }, time = 0.1},
{inputs = { wildpearlpeaseed=1 }, outputs = { geneticmaterial=7 }, time = 0.1},
{inputs = { wildpineappleseed=1 }, outputs = { geneticmaterial=7 }, time = 0.1},
{inputs = { wildpotatoseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { wildporphisplantseed=1 }, outputs = { tissueculture=7 }, time = 0.1},
{inputs = { wildpussplumseed=1 }, outputs = { tissueculture=7 }, time = 0.1},
{inputs = { wildreefpodseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { wildrockrootseed=1 }, outputs = { rawminerals=7 }, time = 0.1},
{inputs = { wildriceseed=1 }, outputs = { geneticmaterial=7 }, time = 0.1},
{inputs = { wildshinyacornseed=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { wildshockshroomseed=1 }, outputs = { tissueculture=11 }, time = 0.1},
{inputs = { wildsilverleafseed=1 }, outputs = { silverore=4 }, time = 0.1},
{inputs = { wildslimeplantseed=1 }, outputs = { greenslime=5 }, time = 0.1},
{inputs = { wildspringvaultseed=1 }, outputs = { tissueculture=3 }, time = 0.1},
{inputs = { wildstranglevineseed=1 }, outputs = { tissueculture=6 }, time = 0.1},
{inputs = { wildsugarcaneseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { wildteratomatoseed=1 }, outputs = { geneticmaterial=13 }, time = 0.1},
{inputs = { wildtalonseedseed=1 }, outputs = { geneticmaterial=7 }, time = 0.1},
{inputs = { wildtetherhookseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { wildthornitoxseed=1 }, outputs = { geneticmaterial=7 }, time = 0.1},
{inputs = { wildtomatoseed=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { wildtoxictopseed=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { wildtyvokkseed=1 }, outputs = { geneticmaterial=8 }, time = 0.1},
{inputs = { wildvaranberryseed=1 }, outputs = { geneticmaterial=2 }, time = 0.1},
{inputs = { wildvextongueseed=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { wildvoritseed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { wildwartweedseed=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { wildwheatseed=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { wildvashtaplantseed=1 }, outputs = { tissueculture=7 }, time = 0.1},
{inputs = { wildwretchelseed=1 }, outputs = { tissueculture=11 }, time = 0.1},
{inputs = { wildwubstemseed=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { wildxaxseed=1 }, outputs = { tissueculture=7 }, time = 0.1},
{inputs = { wildyellowfootseed=1 }, outputs = { tissueculture=7 }, time = 0.1},
{inputs = { wildzathiseed=1 }, outputs = { geneticmaterial=9 }, time = 0.1},
{inputs = { wildkamaranpodsplant=1 }, outputs = { geneticmaterial=8 }, time = 0.1},
{inputs = { wildcellpodsplant=1 }, outputs = { geneticmaterial=7 }, time = 0.1},
{inputs = { wildgoldenseaspongeplant=1 }, outputs = { tissueculture=7 }, time = 0.1},
{inputs = { wildfusnowberryseed=1 }, outputs = { tissueculture=8 }, time = 0.1},
{inputs = { wildspongeweedseed=1 }, outputs = { geneticmaterial=7 }, time = 0.1},
{inputs = { cellpods=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { aenemaflower=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { arkaentree=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { batterystem=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { bellamorte=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { bladetree=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { crystallite=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { darklightflower=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { fletchweed=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { garikleaf=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { herrodbush=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { kramil=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { poetree=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { quellstem=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { tinselbush=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { victorleaf=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { whitespine=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
-- food / produce / plant biproduct
--from FU
{inputs = { hops=1 }, outputs = { geneticmaterial=2 }, time = 0.1},
{inputs = { cotton=1 }, outputs = { geneticmaterial=2 }, time = 0.1},
{inputs = { cinnamon=1 }, outputs = { geneticmaterial=2 }, time = 0.1},
{inputs = { aquapod=1 }, outputs = { tissueculture=6 }, time = 0.1},
{inputs = { beetlesproutflower=1 }, outputs = { tissueculture=6 }, time = 0.1},
{inputs = { biscorn=1 }, outputs = { tissueculture=9 }, time = 0.1},
{inputs = { blexsap=1 }, outputs = { tissueculture=6 }, time = 0.1},
{inputs = { blisterbushplantfood=1 }, outputs = { tissueculture=3 }, time = 0.1},
{inputs = { blizzberry=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { bloodroot=1 }, outputs = { tissueculture=6 }, time = 0.1},
{inputs = { bluemelon=1 }, outputs = { tissueculture=6 }, time = 0.1},
{inputs = { capriole=1 }, outputs = { tissueculture=8 }, time = 0.1},
{inputs = { crystalplant=1 }, outputs = { tissueculture=12 }, time = 0.1},
{inputs = { diodiahybrid=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { dragonsbeard=1 }, outputs = { tissueculture=9 }, time = 0.1},
{inputs = { energiflower=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { fayshroom=1 }, outputs = { tissueculture=6 }, time = 0.1},
{inputs = { floralytcandy=1 }, outputs = { tissueculture=6 }, time = 0.1},
{inputs = { gazelemon=1 }, outputs = { tissueculture=6 }, time = 0.1},
{inputs = { genesiberry=1 }, outputs = { tissueculture=16 }, time = 0.1},
{inputs = { ghostmushroom=1 }, outputs = { tissueculture=12 }, time = 0.1},
{inputs = { ginseng=1 }, outputs = { tissueculture=9 }, time = 0.1},
{inputs = { glarestalkeye=1 }, outputs = { geneticmaterial=22 }, time = 0.1},
{inputs = { goldenglowleaf=1 }, outputs = { tissueculture=12 }, time = 0.1},
{inputs = { goldenroot=1 }, outputs = { tissueculture=12 }, time = 0.1},
{inputs = { goldshroom=1 }, outputs = { tissueculture=12 }, time = 0.1},
{inputs = { greenleaf=1 }, outputs = { tissueculture=12 }, time = 0.1},
{inputs = { guam=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { haleflowerpetal=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { ighantbulb=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { itahead=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { jillyroot=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { lactariusindigo=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { lasherstem=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { leafshell=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { littlegoodberry=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { littlerascal=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { vanusflower=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { melodistar=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { minkocoapod=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { mint=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { miraclegrass=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { mireurchin=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { nailery=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { neuropod=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { nisscap=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { nyanifruit=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { onion=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { pasaka=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { pearlfruit=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { pekkit=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { petrifiedroot=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { pinkloom=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { porphisblossom=1 }, outputs = { tissueculture=4 }, time = 0.1},
{inputs = { rockroot=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { shinyacorn=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { silverleaf=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { slimeleaf=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { springvaultcoil=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { stranglevineroot=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { talonseed=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { tearnut=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { teratomato=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { tetherhookwheel=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { thornitox=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { toxicflower=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { tyvokkhook=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { varanberry=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { vashtaclaw=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { vextonguestamen=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { voritcap=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { wretchel=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { wubstem=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { xaxwing=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { yellowfoot=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { zathitails=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { erithianalgae=1 }, outputs = { tissueculture=10 }, time = 0.1},
{inputs = { peach=1 }, outputs = { tissueculture=10 }, time = 5},
{inputs = { pear=1 }, outputs = { tissueculture=10 }, time = 5},
{inputs = { kamaranpods=1 }, outputs = { tissueculture=10 }, time = 5},
{inputs = { cellpods=1 }, outputs = { tissueculture=10 }, time = 5},
{inputs = { goldenseasponge=1 }, outputs = { tissueculture=10 }, time = 5},
{inputs = { fusnowberry=1 }, outputs = { tissueculture=10 }, time = 5},
{inputs = { fuspongeweed=1 }, outputs = { tissueculture=10 }, time = 5},
{inputs = { aenemapetal=1 }, outputs = { shadowgasliquid=1 }, time = 0.1},
{inputs = { arkaendart=1 }, outputs = { tissueculture=8 }, time = 0.1},
{inputs = { batterystemcharge=1 }, outputs = { tissueculture=8 }, time = 0.1},
{inputs = { bellamortecore=1 }, outputs = { tissueculture=8 }, time = 0.1},
{inputs = { bladetreeblade=1 }, outputs = { tissueculture=8 }, time = 0.1},
{inputs = { crystalliteshard=1 }, outputs = { tissueculture=8 }, time = 0.1},
{inputs = { darklightblossom=1 }, outputs = { tissueculture=8 }, time = 0.1},
{inputs = { fletchweedstem=1 }, outputs = { tissueculture=8 }, time = 0.1},
{inputs = { garikleafblossom=1 }, outputs = { tissueculture=8 }, time = 0.1},
{inputs = { herrodbushgem=1 }, outputs = { tissueculture=8 }, time = 0.1},
{inputs = { kramilspine=1 }, outputs = { tissueculture=8 }, time = 0.1},
{inputs = { quellstembud=1 }, outputs = { tissueculture=8 }, time = 0.1},
{inputs = { tinselbushsprout=1 }, outputs = { tissueculture=8 }, time = 0.1},
{inputs = { victorleafbud=1 }, outputs = { tissueculture=8 }, time = 0.1},
{inputs = { whitespineshell=1 }, outputs = { tissueculture=8 }, time = 0.1},

--from vanilla
{inputs = { plantfibre=50 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { alienfruit=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { boltbulb=1 }, outputs = { rawminerals=3 }, time = 0.1},
{inputs = { cacti=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { chili=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { carrot=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { coffeebeans=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { coralcreep=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { corn=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { crystalplant=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { currentcorn=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { diodia=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { dirturchin=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { eggshoot=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { feathercrown=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { grapes=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { greenapple=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { kelp=12 }, outputs = { iodine=3 }, time = 0.1},
{inputs = { kiwi=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { neonmelon=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { oculemon=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { orange=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { pearlpea=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { pineapple=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { potato=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { pussplum=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { redapple=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { reefpod=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { rice=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { shroom=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { sugar=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { thornfruit=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { tomato=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { toxictop=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { wartweed=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { wheat=1 }, outputs = { tissueculture=5 }, time = 0.1},
{inputs = { alienmeat=1 }, outputs = { geneticmaterial=8 }, time = 0.1},
{inputs = { cookedalienmeat=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { cookedbacon=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { cookedfish=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { cookedfleshlump=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { cookedham=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { cookedpoultry=1 }, outputs = { geneticmaterial=6 }, time = 0.1},
{inputs = { cookedribmeat=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { cookedtentacle=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { meatchunks=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { offal=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { rawpoultry=1 }, outputs = { geneticmaterial=4 }, time = 0.1},
{inputs = { rawbacon=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { rawfish=1 }, outputs = { geneticmaterial=5 }, time = 0.1},
{inputs = { rawfleshlump=1 }, outputs = { geneticmaterial=8 }, time = 0.1},
{inputs = { soylentgreen=1 }, outputs = { geneticmaterial=8 }, time = 0.1},
{inputs = { rawribmeat=1 }, outputs = { geneticmaterial=8 }, time = 0.1},
{inputs = { rawtentacle=1 }, outputs = { geneticmaterial=8 }, time = 0.1},
{inputs = { wildvines=1 }, outputs = { tissueculture=7 }, time = 0.1},
{inputs = { coconut=1 }, outputs = { tissueculture=7 }, time = 0.1},
{inputs = { hivebomb=1 }, outputs = { tissueculture=8 }, time = 0.1},
{inputs = { raptoregg=1 }, outputs = { geneticmaterial=12 }, time = 0.1},
{inputs = { carcass1=1 }, outputs = { tissueculture=24,geneticmaterial=24  }, time = 0.1},
{inputs = { carcass2=1 }, outputs = { tissueculture=24,geneticmaterial=24  }, time = 0.1},
-- vanilla ores
{inputs = { coalore=12 }, outputs = { fu_carbon=1 }, time = 0.1},
{inputs = { copperore=1 }, outputs = { rawminerals=6 }, time = 0.1},
{inputs = { ironore=1 }, outputs = { liquidironfu=4 }, time = 0.1},
{inputs = { silverore=1 }, outputs = { rawminerals=8 }, time = 0.1},
{inputs = { goldore=1 }, outputs = { rawminerals=8 }, time = 0.1},
{inputs = { corefragmentore=2 }, outputs = { ammoniumsulfate=2, volatilepowder=2 }, time = 0.1},
{inputs = { aegisaltore=1 }, outputs = { rawminerals=9 }, time = 0.1},
{inputs = { platinumore=1 }, outputs = { rawminerals=9 }, time = 0.1},
{inputs = { prisiliteore=1 }, outputs = { rawminerals=10 }, time = 0.1},
{inputs = { plutoniumore=1 }, outputs = { matteritem=6 }, time = 0.1},
{inputs = { feroziumore=1 }, outputs = { rawminerals=8 }, time = 0.1},
{inputs = { moonstoneore=1 }, outputs = { rawminerals=8 }, time = 0.1},
{inputs = { solariumore=1 }, outputs = { rawminerals=8 }, time = 0.1},
{inputs = { sulphur=1 }, outputs = { liquidsulphuricacid=4 }, time = 0.1},
{inputs = { titaniumore=1 }, outputs = { rawminerals=9 }, time = 0.1},
{inputs = { triangliumore=1 }, outputs = { rawminerals=8 }, time = 0.1},
{inputs = { uraniumore=1 }, outputs = { matteritem=7 }, time = 0.1},
{inputs = { lead=1 }, outputs = { rawminerals=7 }, time = 0.1},
{inputs = { diamond=1 }, outputs = { fu_carbon=11 }, time = 0.1},
{inputs = { violiumore=1 }, outputs = { rawminerals=9 }, time = 0.1},
-- fu ores
{inputs = { mascagniteore=4 }, outputs = { ammoniumsulfate=2 }, time = 0.1},
{inputs = { lazuliteore=4 }, outputs = { phosphorus=2 }, time = 0.1},
{inputs = { magnesiumore=4 }, outputs = { magnesiumpowder=2 }, time = 0.1},
{inputs = { irradiumore=4 }, outputs = { rawminerals=5 }, time = 0.1},
{inputs = { protociteore=4 }, outputs = { rawminerals=10 }, time = 0.1},
{inputs = { penumbriteore=4 }, outputs = { rawminerals=10 }, time = 0.1},
{inputs = { cinnabarore=4 }, outputs = { rawminerals=10 }, time = 0.1},
{inputs = { densiniumore=4 }, outputs = { rawminerals=24 }, time = 0.1},
{inputs = { berliniteore=4 }, outputs = { phosphorus=3 }, time = 0.1},
{inputs = { corruptionore=4 }, outputs = { rawminerals=7 }, time = 0.1},
{inputs = { solarishard=20 }, outputs = { crystal=2 }, time = 0.1},
{inputs = { solaricrystal=1 }, outputs = { solarishard=3 }, time = 0.1},
{inputs = { matteritem=50 }, outputs = { unstableparticles=2 }, time = 0.1},
{inputs = { zerchesiumore=4 }, outputs = { fu_carbon=12 }, time = 0.1},
{inputs = { rawminerals=4 }, outputs = { lead=2 }, time = 0.1}
}

function init(args)
    if args then return end
    self.timer = 0
    self.mintick = 0
    self.crafting = false
    self.output = {}
	storage.activeConsumption = false
end

function getInputContents()
        local id = entity.id()
      
        local contents = {}
        for i=0,2 do
            local stack = world.containerItemAt(entity.id(),i)
            if stack ~=nil then
                if contents[stack.name] ~= nil then
                  contents[stack.name] = contents[stack.name] + stack.count
                else
                  contents[stack.name] = stack.count
                end
            end
        end
      
        return contents
    end

function map(l,f)
    local res = {}
    for k,v in pairs(l) do
        res[k] = f(v)
    end
    return res
end

function filter(l,f)
  return map(l, function(e) return f(e) and e or nil end)
end

function getValidRecipes(query)

    local function subset(t1,t2)
        if next(t2) == nil then 
          return false 
        end
        if t1 == t2 then 
          return true
        end
            for k,_ in pairs(t1) do
                if not t2[k] or t1[k] > t2[k] then 
                  return false 
                end
            end
        return true
    end

return filter(recipes, function(l) return subset(l.inputs, query) end)

end


function getOutSlotsFor(something)
    local empty = {} -- empty slots in the outputs
    local slots = {} -- slots with a stack of "something"

    for i = 3, 11 do -- iterate all output slots
        local stack = world.containerItemAt(entity.id(), i) -- get the stack on i
        if stack ~= nil then -- not empty
            if stack.name == something then -- its "something"
                table.insert(slots,i) -- possible drop slot
            end
        else -- empty
            table.insert(empty, i)
        end
    end

    for _,e in pairs(empty) do -- add empty slots to the end
        table.insert(slots,e)
    end
    return slots
end


function update(dt)
  if isn_hasRequiredPower() == false then
    animator.setAnimationState("samplingarrayanim", "idle")
    object.setLightColor({0, 0, 0, 0})
	storage.activeConsumption = false
	return
  end
    self.timer = self.timer - dt
    if self.timer <= 0 then
        if self.crafting then
            for k,v in pairs(self.output) do
                local leftover = {name = k, count = v}
                local slots = getOutSlotsFor(k)
                for _,i in pairs(slots) do
                    leftover = world.containerPutItemsAt(entity.id(), leftover, i)
                    if leftover == nil then
                        break
                    end
                end

                if leftover ~= nil then
                    world.spawnItem(leftover.name, entity.position(), leftover.count)
                end
            end
            self.crafting = false
            self.output = {}
            self.timer = self.mintick --reset timer to a safe minimum
            animator.setAnimationState("samplingarrayanim", "idle")
            object.setLightColor({0, 0, 0, 0})
			storage.activeConsumption = false
        end

        if not self.crafting and self.timer <= 0 then --make sure we didn't just finish crafting
            if not startCrafting(getValidRecipes(getInputContents())) then self.timer = self.mintick end --set timeout if there were no recipes
        end
    end
end



function startCrafting(result)
    if next(result) == nil then return false
    else _,result = next(result)

        for k,v in pairs(result.inputs) do
            if not world.containerConsume(entity.id(), {item = k , count = v}) then return false end
        end

        self.crafting = true
        self.timer = result.time
        self.output = result.outputs
        animator.setAnimationState("samplingarrayanim", "working")
        object.setLightColor(config.getParameter("lightColor", {100, 176, 191}))
		storage.activeConsumption = true
        return true
    end              
end