name: JSON linter + luacheck

on: [push, pull_request, workflow_dispatch]

jobs:
  # Check JSON assets for syntax errors.
  json-linter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: ( cd tests/travis && npm install )

      - name: RUN -- npm test
        run: ( cd tests/travis && npm test )

  # Check Lua files with "luacheck" tool (Lua static analyzer).
  luacheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y luarocks && sudo luarocks install luacheck
      - name: RUN -- luacheck .
        run: luacheck --no-color --quiet .

  # Detect non-optimized PNG images (where lossless compression can seriously reduce their filesize).
  unoptimized-png-images:
    if: ${{ github.base_ref || github.ref != 'refs/heads/master' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y optipng
      - run: .github/scripts/detect-unoptimized-png-images.sh

  # Create .pak file for each GitHub release.
  pack-assets:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Remove directories that are not needed inside PAK file (e.g. ".git" or "tests")
        run: rm -rf .git a_modders tests
      - uses: edwardspec/github-action-pack-starbound-mod@v1
        with:
          outputFilename: FrackinUniverse.pak
      - run: ls -l FrackinUniverse.pak
      - name: Add .pak file to release
        uses: softprops/action-gh-release@v1
        with:
          files: FrackinUniverse.pak
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
